### PR TITLE
changed filter to snapshot_tags, similar to ec2_snapshot.

### PR DESCRIPTION
**Pull request by bonovoxly**
Instead of specifying filter, I changed it to be more similar to ec2_snapshot.  When specifying the option "snapshot_tags", the user specifies a dictionary of tag key/value pairs.  Example:

```
- name: Find snapshot of the volume.
  ec2_snapshot_facts:
    aws_secret_key: "{{aws_secret_key}}"
    aws_access_key: "{{aws_access_key}}"
    region: "{{ami_region}}"
    snapshot_tags:
      tag1: value1
      tag2:  value2
  register: snapshots_found

- name: Debug snapshot search.
  debug:
    msg: "{{snapshot_found}}"

```

Documentation not updated. Probably needs thorough testing.

### CODE REVIEW

**Comment by bonovoxly** [comment]
I added the ability to search by volume_id as well.

**Comment by wimnat** [comment]
Filters allow you to search by everything: tags, id etc - see http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeSnapshots.html

It is similar to how the other AWS _facts modules work and is based on how boto works so I think it's best to keep filters as the parameter

**Comment by bonovoxly** [comment]
gotcha.  are the newer ansible modules moving towards filters?  i was simply mimicking the functionality of those.

**Comment by wimnat** [comment]
So ec2_eni_facts, ec2_vpc_*_facts, ec2_remote_facts etc all uses the filters parameter.  These are 2.0 modules.  I think any new modules going forward will also use this functionality.

**Comment by bonovoxly** [comment]
Ahhh, gotcha.  Cool, thanks for the info!  Nice module.

**Comment by wimnat** [comment]
Thanks :) Please do add the "works_for_me" comment to https://github.com/ansible/ansible-modules-extras/pull/1088 as this will help it get merged :+1:

**Pull request closed without merging**
